module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        error: "var(--error)",
        onBackground: "var(--onBackground)",
        onError: "var(--onError)",
        primary: "var(--primary)",
        primaryVariant: "var(--primaryVariant)",
        onPrimary: "var(--onPrimary)",
        secondary: "var(--secondary)",
        secondaryVariant: "var(--secondaryVariant)",
        onSecondary: "var(--onSecondary)",
        surface: "var(--surface)",
        onSurface: "var(--onSurface)",
      },
      textColor: {
        primary: "var(--primary)",
        primaryVariant: "var(--primaryVariant)",
        secondary: "var(--secondary)",
        secondaryVariant: "var(--secondaryVariant)",
        primaryTextColor: "var(--primaryTextColor)",
        secondaryTextColor: "var(--secondaryTextColor)",
        error: "var(--error)",
      },
      backgroundColor: {
        background: "var(--background)",
        onBackground: "var(--onBackground)",
        primary: "var(--primary)",
        primaryVariant: "var(--primaryVariant)",
        onPrimary: "var(--onPrimary)",
        secondary: "var(--secondary)",
        secondaryVariant: "var(--secondaryVariant)",
        onSecondary: "var(--onSecondary)",
        surface: "var(--surface)",
        onSurface: "var(--onSurface)",
      },
      fill: {
        background: "var(--background)",
        error: "var(--error)",
        onBackground: "var(--onBackground)",
        onError: "var(--onError)",
        primary: "var(--primary)",
        primaryVariant: "var(--primaryVariant)",
        onPrimary: "var(--onPrimary)",
        secondary: "var(--secondary)",
        secondaryVariant: "var(--secondaryVariant)",
        onSecondary: "var(--onSecondary)",
        surface: "var(--surface)",
        onSurface: "var(--onSurface)",
      },
      height: {
        0.5: "0.5px",
        14: "3.5rem",
        "1/4-screen": "25vh",
        "1/3-screen": "33vh",
        "1/2-screen": "50vh",
        350: "350px",
        500: "500px",
      },
      width: {
        0.5: "0.5px",
        "1/16": "6.25%",
        "2/16": "12.5%",
        "3/16": "18.75%",
        "4/16": "25%",
        "5/16": "31.25%",
        "6/16": "37.5%",
        "7/16": "43.75%",
        "8/16": "50%",
        "9/16": "56.25%",
        "10/16": "62.5%",
        "11/16": "68.75%",
        "12/16": "75%",
        "13/16": "81.25%",
        "14/16": "87.5%",
        "15/16": "93.75%",
        "16/16": "100%",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        DEFAULT: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
        md: "0 0px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        "md-primary": "0 0px 6px -1px var(--primary), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        "3xl": "0 35px 60px -15px rgba(0, 0, 0, 0.3)",
        inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
        none: "none",
        primary: "0px 0px 6px 4px var(--primary), 0px 2px 4px 0px var(--primary)",
      },
      margin: {
        14: "3.5rem",
      },
      padding: {
        14: "3.5rem",
      },
    },
    fontFamily: {
      mulish: ["Mulish", "sans-serif"],
    },
  },
  variants: {
    fill: ["responsive", "hover"],
  },
  plugins: [],
};
